on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Send slack notification bash
        id: slack
        uses: tzahibar/docker-slack-notify@main
        with:
          who-to-greet: 'tzahi'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
